export const filterData = [
  {name: 'Fast food', image: require('./../../assets/icons/icon1.png'), id: 1},
  {name: 'Burgers', image: require('./../../assets/icons/icon2.png'), id: 2},
  {name: 'Salad', image: require('./../../assets/icons/icon3.png'), id: 3},
  {name: 'Desert', image: require('./../../assets/icons/icon4.png'), id: 4},
  {name: 'Chinese', image: require('./../../assets/icons/icon5.png'), id: 5},
  {name: 'Mexican', image: require('./../../assets/icons/icon6.png'), id: 6},
];
export const filterData2 = [
  {
    name: 'Fast food',
    image: 'https://bukasapics.s3.us-east-2.amazonaws.com/chicken.png',
    id: 1,
  },
  {
    name: 'Burgers',
    image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
    id: 2,
  },
  {
    name: 'Salad',
    image: 'https://bukasapics.s3.us-east-2.amazonaws.com/macdo.png',
    id: 3,
  },
  {
    name: 'Desert',
    image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
    id: 4,
  },
  {
    name: 'Chinese',
    image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate2.png',
    id: 5,
  },
  {
    name: 'Mexican',
    image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate1.png',
    id: 6,
  },
];

export const resturantsData = [
  {
    resturantName: 'Mc Donalds',
    farAway: '21.2',
    businessAddress: '22 Bessie street, Cape Town',
    images: 'https://bukasapics.s3.us-east-2.amazonaws.com/chicken.png',
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {lat: -26.1888612, lng: 28.246325},
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: 'Burgers, Wraps, Milkshakes...',
    productData: [
      {
        id: 0,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        id: 1,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        name: 'Big mac',
        price: 50.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        id: 2,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 0,
  },
  {
    resturantName: 'KFC',
    farAway: '12.7',
    businessAddress: '22 Bessie street, Cape Town',
    images: 'https://bukasapics.s3.us-east-2.amazonaws.com/macdo.png',
    averageReview: 4.3,
    numberOfReview: 309,
    coordinates: {lat: -26.1891648, lng: 28.2441808},
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: 'Chicken, Chicken wings',
    productData: [
      {
        id: 3,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        id: 4,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        name: 'Big mac',
        price: 50.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        id: 5,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 1,
  },
  {
    resturantName: 'Steers',
    farAway: '22.2',
    businessAddress: '22 Bessie street, Cape Town',
    images: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {lat: -26.1888612, lng: 28.246325},
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: 'Flame grilled beef burgers',
    productData: [
      {
        id: 6,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        id: 7,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        name: 'Big mac',
        price: 50.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        id: 8,
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit',
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 2,
  },
];

export const menuData = [
  {title: 'BEEF', special: false, key: 0},
  {title: 'HOT DRINKS', special: false, key: 1},
  {title: 'CHICKEN', special: false, key: 2},
  {title: 'VEGGIE BURGER', special: false, key: 3},
  {title: 'FRIES & CORN', special: false, key: 4},
  {title: 'SALADS', special: false, key: 5},
  {title: 'HAPPY MEALS', special: false, key: 6},
  {title: 'SAHRE BOX', special: false, key: 7},
  {title: 'MILKSHAKES', special: false, key: 8},
  {title: 'COLD DRINKS', special: false, key: 9},
  {title: 'DESSERTS', special: false, key: 10},
];
export const specialData = [
  {title: 'LIMITED OFFER', key: 0},
  {title: 'GO CHILLI', key: 1},
  {title: 'GO CHEESE', key: 2},
  {title: 'MCCHICKEN DELUXE PROMO', key: 3},
];
